num_infected: 2
num_non_infected_per_room: 4
num_hours: 240
delta_t: 1
dose_shape1: 1
dose_shape2: 15
initial_virus_nasal: 0.001
initial_virus_serum: 0.001
k_dose: 0.2
nasal_threshold_mean: 7.98
nasal_shape: 2
serum_threshold_mean: 10.83
serum_threshold_sd: 0.903
infect_threshold_mean: 5.8
infect_threshold_sd: 0.7337373
growth_rate_nasal_mean: 4.1
growth_rate_nasal_sd: 0.1
growth_rate_serum_mean: 3.0
growth_rate_serum_sd: 0.3
clearance_rate_mean: 1.0
clearance_rate_sd: 0.1
stochastic_noise_mean: 0.21
stochastic_noise_sd: 0.05
exponential_factor_mean: 0.5
exponential_factor_sd: 0.15
inflection_point_mean: 4
inflection_point_sd: 0.5
growth_cease_mean: 240
growth_cease_sd: 10
nasal_ccap_mean: 10
nasal_ccap_sd: 0.5
serum_ccap_mean: 10
serum_ccap_sd: 0.5
num_rooms: 5
donor_move_interval: 24
