# Simulation Duration
num_hours: 720
delta_t: 1

# Initial Seeding
num_donors: 0
initial_donors:
  farm_1: 2
total_herd_size: 100

# Transmission Model
contact_rate: 0.15
dose_scaling_factor: 10
dose_max_efficiency: 0.4
dose_efficiency_at_threshold: 0.15
dose_threshold: 0.8

# Virus Dynamics (Titer-Based Models Only)
nasal_threshold_mean: 7.8
nasal_threshold_sd: 0.2
serum_threshold_mean: 6.7
serum_threshold_sd: 0.2
infect_threshold_mean: 6.1
infect_threshold_sd: 0.2
growth_rate_nasal_mean: 3.1
growth_rate_nasal_sd: 0.2
growth_rate_serum_mean: 2.6
growth_rate_serum_sd: 0.2
clearance_rate_mean: 0.6
clearance_rate_sd: 0.2
stochastic_noise_mean: 0.5
stochastic_noise_sd: 0.2
exponential_factor_mean: 1.1
exponential_factor_sd: 0.2
inflection_point_mean: 5.6
inflection_point_sd: 0.2
growth_cease_mean: 120
growth_cease_sd: 2
nasal_ccap_mean: 10
nasal_ccap_sd: 0.2
serum_ccap_mean: 9
serum_ccap_sd: 0.2

# Probabilistic Progression Parameters
preclin_infect: TRUE
recovery_time_mean: 12         # days
recovery_time_sd: 1            # days
preclin_onset_median: 1.25     # days
preclin_onset_ci: [0.8, 2.1]
preclin_duration_median: 2.05  # days
preclin_duration_ci: [1.2, 2.9]
clinical_duration_median: 6.0  # days
clinical_duration_ci: [5.0, 7.0]

# Between-Herd Network Parameters
n_farms: 20
herd_size_range: [80, 120]
graph_type: erdos          # erdos, smallworld, geometric
shape_gamma: 2
scale_gamma: 5
lambda: 0.001                  # for weight = exp(-lambda * distance)

# Between-Herd Movement
movement_prob: 0.1
movement_interval: 24
animals_moved_frac: 0.20
transmission_prob: 0.5
detection_delay_hours: 120
detection_triggers_quarantine: TRUE
seed: 1980
